version: '3.8'

services:
  backend:
    image: openjdk:23-jdk
    container_name: springboot-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Marketplace
        SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
        - db

  frontend:
    image: node:18-alpine # Use Node.js to serve React build
    container_name: react-frontend
    build:
      context: ./frontend # Path to your React frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./frontend:/usr/src/app # Optional: Mount for local development
    command: sh -c "npm install && npm start"

  db:
    image: mysql:8.0 # MySQL image
    container_name: mysql-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
